cc_library(
    name = "util",
    hdrs = [
        "Field-Util.h",
    ],
    visibility = [
        "//eval:__pkg__",
        "//eval/util:__pkg__",
        "//operation/field:__pkg__",
    ],
    deps = [
        "@boost//:smart_ptr",
        "//math:base",
    ],
)
