load("//third_party:cppenum.bzl", "gen_cppenum")

gen_cppenum(
    enum_file="PrunningEnum.yaml",
    visibility = ["//runprofile:__pkg__",],
)

gen_cppenum(
    enum_file="UnivInterpEnum.yaml",
    visibility = ["//runprofile:__pkg__",],
)

gen_cppenum(
    enum_file="VandSolveTypeEnum.yaml",
    visibility = ["//runprofile:__pkg__",],
)

gen_cppenum(
    enum_file="VarOrderEnum.yaml",
    visibility = ["//runprofile:__pkg__",],
)