cc_library(
    name = "benchmark",
    hdrs = [
        "benchmark.h",
        "FieldOperations.h",
        "Operation.h",
    ],
    deps = [
        "//complexity:equation",
        "//complexity:tracker",
        "//external:boost-timer",
        "//math:base",
        "//util:log",
    ],
    visibility = [
        "//run:__pkg__",
    ]
)