cc_library(
    name = "algorithm",
    hdrs = [
        "algorithm.h",
        "algorithm-impl.h",
    ],
    srcs = [
        "algorithm.cpp",
    ],
    deps = [
        "//math:base",
        "//external:boost-smart_ptr",
        "//util:log",
        "//util:smart_assert",
    ],
    visibility = [
        "//math/vandermonde:__pkg__",
    ],
)