cc_library(
    name = "command_line",
    srcs = [
        "CommandLine.cpp",
    ],
    hdrs = [
        "CommandLine.h",
    ],
    visibility = [
        "//:__pkg__",
        "//runprofile:__pkg__",
    ],
    deps = [
        "//external:boost-algorithm",
        "//external:boost-bind",
        "//external:boost-program_options",
        "//external:boost-static_assert",
        "//external:boost-type_traits",
        "//runprofile",
    ],
)
