cc_library(
    name = "benchmark",
    hdrs = [
        "benchmark.h",
    ],
    deps = [
        "//complexity:equation",
        "//complexity:tracker",
        "//math/vandermonde:fft_solver",
        "//math/vandermonde:quad_solver",
        "//external:boost-smart_ptr",
        "//external:boost-timer",
        "//math:base",
    ],
    visibility = [
        "//run:__pkg__",
    ]
)