cc_library(
    name = "field_uint",
    hdrs = [
        "Field_uint.h",
        "Field_uint-Impl.h",
    ],
    deps = [
        "//math:base",
        "//math/util:modular-x86",
        "//math/util:random",
        "//math/util:static",
    ],
    visibility = [
        "//run:__pkg__",
    ],

)

cc_library(
    name = "field_uint2x",
    hdrs = [
        "Field_uint2x.h",
        "Field_uint2x-Impl.h",
    ],
    deps = [
        "//math:base",
        "//math/util:modular-x86",
        "//math/util:random",
        "//math/util:static",
    ],
    visibility = [
        "//run:__pkg__",
    ],
)

cc_library(
    name = "field_uint2x32",
    hdrs = [
        "Field_uint2x32.h",
        "Field_uint2x32-Impl.h",
    ],
    deps = [
        "//math:base",
        "//math/util:modular-x86",
        "//math/util:random",
        "//math/util:static",
    ],
    visibility = [
    ],
)