load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

new_git_repository(
    name = "com_github_google_googletest",
    build_file = "@//third_party:googletest.BUILD",
    remote = "https://github.com/google/googletest.git",
    tag = "release-1.7.0",
)

bind(
    name = "googletest",
    actual = "@com_github_google_googletest//:googletest",
)

bind(
    name = "googletest/license",
    actual = "@com_github_google_googletest//:license",
)

new_git_repository(
    name = "com_github_cherba29_cppenum",
    build_file = "@//third_party:cppenum.BUILD",
    remote = "https://github.com/cherba29/cppenum.git",
    commit = "6e12d4d9ed574ab5361b5f08bb80ce455fc2c54a",
)

bind(
    name = "gen_cppenum",
    actual = "@com_github_cherba29_cppenum//:gen_cppenum",
)

## Boost

BOOST_RELEASE_TAG = "boost-1.62.0"

# algorithm

new_git_repository(
    name = "com_github_boost_algorithm",
    build_file = "@//third_party/boost:algorithm.BUILD",
    remote = "https://github.com/boostorg/algorithm.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-algorithm",
    actual = "@com_github_boost_algorithm//:algorithm",
)

# align

new_git_repository(
    name = "com_github_boost_align",
    build_file = "@//third_party/boost:align.BUILD",
    remote = "https://github.com/boostorg/align.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-align",
    actual = "@com_github_boost_align//:align",
)

# any

new_git_repository(
    name = "com_github_boost_any",
    build_file = "@//third_party/boost:any.BUILD",
    remote = "https://github.com/boostorg/any.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-any",
    actual = "@com_github_boost_any//:any",
)

# array

new_git_repository(
    name = "com_github_boost_array",
    build_file = "@//third_party/boost:array.BUILD",
    remote = "https://github.com/boostorg/array.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-array",
    actual = "@com_github_boost_array//:array",
)

# asio

new_git_repository(
    name = "com_github_boost_asio",
    build_file = "@//third_party/boost:asio.BUILD",
    remote = "https://github.com/boostorg/asio.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-asio",
    actual = "@com_github_boost_asio//:asio",
)

# assert

new_git_repository(
    name = "com_github_boost_assert",
    build_file = "@//third_party/boost:assert.BUILD",
    remote = "https://github.com/boostorg/assert.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-assert",
    actual = "@com_github_boost_assert//:assert",
)

# atomic

new_git_repository(
    name = "com_github_boost_atomic",
    build_file = "@//third_party/boost:atomic.BUILD",
    remote = "https://github.com/boostorg/atomic.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-atomic",
    actual = "@com_github_boost_atomic//:atomic",
)

# bind

new_git_repository(
    name = "com_github_boost_bind",
    build_file = "@//third_party/boost:bind.BUILD",
    remote = "https://github.com/boostorg/bind.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-bind",
    actual = "@com_github_boost_bind//:bind",
)

# chrono

new_git_repository(
    name = "com_github_boost_chrono",
    build_file = "@//third_party/boost:chrono.BUILD",
    remote = "https://github.com/boostorg/chrono.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-chrono",
    actual = "@com_github_boost_chrono//:chrono",
)

# concept_check

new_git_repository(
    name = "com_github_boost_concept_check",
    build_file = "@//third_party/boost:concept_check.BUILD",
    remote = "https://github.com/boostorg/concept_check.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-concept_check",
    actual = "@com_github_boost_concept_check//:concept_check",
)

# config

new_git_repository(
    name = "com_github_boost_config",
    build_file = "@//third_party/boost:config.BUILD",
    remote = "https://github.com/boostorg/config.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-config",
    actual = "@com_github_boost_config//:config",
)

# container

new_git_repository(
    name = "com_github_boost_container",
    build_file = "@//third_party/boost:container.BUILD",
    remote = "https://github.com/boostorg/container.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-container",
    actual = "@com_github_boost_container//:container",
)

# core

new_git_repository(
    name = "com_github_boost_core",
    build_file = "@//third_party/boost:core.BUILD",
    remote = "https://github.com/boostorg/core.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-core",
    actual = "@com_github_boost_core//:core",
)

# detail

new_git_repository(
    name = "com_github_boost_detail",
    build_file = "@//third_party/boost:detail.BUILD",
    remote = "https://github.com/boostorg/detail.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-detail",
    actual = "@com_github_boost_detail//:detail",
)

# date_time

new_git_repository(
    name = "com_github_boost_date_time",
    build_file = "@//third_party/boost:date_time.BUILD",
    remote = "https://github.com/boostorg/date_time.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-date_time",
    actual = "@com_github_boost_date_time//:date_time",
)

# exception

new_git_repository(
    name = "com_github_boost_exception",
    build_file = "@//third_party/boost:exception.BUILD",
    remote = "https://github.com/boostorg/exception.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-exception",
    actual = "@com_github_boost_exception//:exception",
)

# filesystem

new_git_repository(
    name = "com_github_boost_filesystem",
    build_file = "@//third_party/boost:filesystem.BUILD",
    remote = "https://github.com/boostorg/filesystem.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-filesystem",
    actual = "@com_github_boost_filesystem//:filesystem",
)

# foreach

new_git_repository(
    name = "com_github_boost_foreach",
    build_file = "@//third_party/boost:foreach.BUILD",
    remote = "https://github.com/boostorg/foreach.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-foreach",
    actual = "@com_github_boost_foreach//:foreach",
)

# function

new_git_repository(
    name = "com_github_boost_function",
    build_file = "@//third_party/boost:function.BUILD",
    remote = "https://github.com/boostorg/function.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-function",
    actual = "@com_github_boost_function//:function",
)

# function_types

new_git_repository(
    name = "com_github_boost_function_types",
    build_file = "@//third_party/boost:function_types.BUILD",
    remote = "https://github.com/boostorg/function_types.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-function_types",
    actual = "@com_github_boost_function_types//:function_types",
)

# functional

new_git_repository(
    name = "com_github_boost_functional",
    build_file = "@//third_party/boost:functional.BUILD",
    remote = "https://github.com/boostorg/functional.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-functional",
    actual = "@com_github_boost_functional//:functional",
)

# fusion

new_git_repository(
    name = "com_github_boost_fusion",
    build_file = "@//third_party/boost:fusion.BUILD",
    remote = "https://github.com/boostorg/fusion.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-fusion",
    actual = "@com_github_boost_fusion//:fusion",
)

# integer

new_git_repository(
    name = "com_github_boost_integer",
    build_file = "@//third_party/boost:integer.BUILD",
    remote = "https://github.com/boostorg/integer.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-integer",
    actual = "@com_github_boost_integer//:integer",
)

# interprocess

new_git_repository(
    name = "com_github_boost_interprocess",
    build_file = "@//third_party/boost:interprocess.BUILD",
    remote = "https://github.com/boostorg/interprocess.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-interprocess",
    actual = "@com_github_boost_interprocess//:interprocess",
)

# intrusive

new_git_repository(
    name = "com_github_boost_intrusive",
    build_file = "@//third_party/boost:intrusive.BUILD",
    remote = "https://github.com/boostorg/intrusive.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-intrusive",
    actual = "@com_github_boost_intrusive//:intrusive",
)

# io

new_git_repository(
    name = "com_github_boost_io",
    build_file = "@//third_party/boost:io.BUILD",
    remote = "https://github.com/boostorg/io.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-io",
    actual = "@com_github_boost_io//:io",
)

# iterator

new_git_repository(
    name = "com_github_boost_iterator",
    build_file = "@//third_party/boost:iterator.BUILD",
    remote = "https://github.com/boostorg/iterator.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-iterator",
    actual = "@com_github_boost_iterator//:iterator",
)

# lexical_cast

new_git_repository(
    name = "com_github_boost_lexical_cast",
    build_file = "@//third_party/boost:lexical_cast.BUILD",
    remote = "https://github.com/boostorg/lexical_cast.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-lexical_cast",
    actual = "@com_github_boost_lexical_cast//:lexical_cast",
)

# locale

new_git_repository(
    name = "com_github_boost_locale",
    build_file = "@//third_party/boost:locale.BUILD",
    remote = "https://github.com/boostorg/locale.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-locale",
    actual = "@com_github_boost_locale//:locale",
)

# log

new_git_repository(
    name = "com_github_boost_log",
    build_file = "@//third_party/boost:log.BUILD",
    remote = "https://github.com/boostorg/log.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-log",
    actual = "@com_github_boost_log//:log",
)

# math

new_git_repository(
    name = "com_github_boost_math",
    build_file = "@//third_party/boost:math.BUILD",
    remote = "https://github.com/boostorg/math.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-math",
    actual = "@com_github_boost_math//:math",
)

# move

new_git_repository(
    name = "com_github_boost_move",
    build_file = "@//third_party/boost:move.BUILD",
    remote = "https://github.com/boostorg/move.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-move",
    actual = "@com_github_boost_move//:move",
)

# mpl

new_git_repository(
    name = "com_github_boost_mpl",
    build_file = "@//third_party/boost:mpl.BUILD",
    remote = "https://github.com/boostorg/mpl.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-mpl",
    actual = "@com_github_boost_mpl//:mpl",
)

# multi_index

new_git_repository(
    name = "com_github_boost_multi_index",
    build_file = "@//third_party/boost:multi_index.BUILD",
    remote = "https://github.com/boostorg/multi_index.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-multi_index",
    actual = "@com_github_boost_multi_index//:multi_index",
)

# numeric_conversion

new_git_repository(
    name = "com_github_boost_numeric_conversion",
    build_file = "@//third_party/boost:numeric_conversion.BUILD",
    remote = "https://github.com/boostorg/numeric_conversion.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-numeric_conversion",
    actual = "@com_github_boost_numeric_conversion//:numeric_conversion",
)

# optional

new_git_repository(
    name = "com_github_boost_optional",
    build_file = "@//third_party/boost:optional.BUILD",
    remote = "https://github.com/boostorg/optional.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-optional",
    actual = "@com_github_boost_optional//:optional",
)

# parameter

new_git_repository(
    name = "com_github_boost_parameter",
    build_file = "@//third_party/boost:parameter.BUILD",
    remote = "https://github.com/boostorg/parameter.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-parameter",
    actual = "@com_github_boost_parameter//:parameter",
)

# phoenix

new_git_repository(
    name = "com_github_boost_phoenix",
    build_file = "@//third_party/boost:phoenix.BUILD",
    remote = "https://github.com/boostorg/phoenix.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-phoenix",
    actual = "@com_github_boost_phoenix//:phoenix",
)

# predef

new_git_repository(
    name = "com_github_boost_predef",
    build_file = "@//third_party/boost:predef.BUILD",
    remote = "https://github.com/boostorg/predef.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-predef",
    actual = "@com_github_boost_predef//:predef",
)

# preprocessor

new_git_repository(
    name = "com_github_boost_preprocessor",
    build_file = "@//third_party/boost:preprocessor.BUILD",
    remote = "https://github.com/boostorg/preprocessor.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-preprocessor",
    actual = "@com_github_boost_preprocessor//:preprocessor",
)

# program_options

new_git_repository(
    name = "com_github_boost_program_options",
    build_file = "@//third_party/boost:program_options.BUILD",
    remote = "https://github.com/boostorg/program_options.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-program_options",
    actual = "@com_github_boost_program_options//:program_options",
)

# property_tree

new_git_repository(
    name = "com_github_boost_property_tree",
    build_file = "@//third_party/boost:property_tree.BUILD",
    remote = "https://github.com/boostorg/property_tree.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-property_tree",
    actual = "@com_github_boost_property_tree//:property_tree",
)

# proto

new_git_repository(
    name = "com_github_boost_proto",
    build_file = "@//third_party/boost:proto.BUILD",
    remote = "https://github.com/boostorg/proto.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-proto",
    actual = "@com_github_boost_proto//:proto",
)

# random

new_git_repository(
    name = "com_github_boost_random",
    build_file = "@//third_party/boost:random.BUILD",
    remote = "https://github.com/boostorg/random.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-random",
    actual = "@com_github_boost_random//:random",
)

# range

new_git_repository(
    name = "com_github_boost_range",
    build_file = "@//third_party/boost:range.BUILD",
    remote = "https://github.com/boostorg/range.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-range",
    actual = "@com_github_boost_range//:range",
)

# ratio

new_git_repository(
    name = "com_github_boost_ratio",
    build_file = "@//third_party/boost:ratio.BUILD",
    remote = "https://github.com/boostorg/ratio.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-ratio",
    actual = "@com_github_boost_ratio//:ratio",
)

# regex

new_git_repository(
    name = "com_github_boost_regex",
    build_file = "@//third_party/boost:regex.BUILD",
    remote = "https://github.com/boostorg/regex.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-regex",
    actual = "@com_github_boost_regex//:regex",
)

# serialization

new_git_repository(
    name = "com_github_boost_serialization",
    build_file = "@//third_party/boost:serialization.BUILD",
    remote = "https://github.com/boostorg/serialization.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-serialization",
    actual = "@com_github_boost_serialization//:serialization",
)

# smart_ptr

new_git_repository(
    name = "com_github_boost_smart_ptr",
    build_file = "@//third_party/boost:smart_ptr.BUILD",
    remote = "https://github.com/boostorg/smart_ptr.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-smart_ptr",
    actual = "@com_github_boost_smart_ptr//:smart_ptr",
)

# spirit

new_git_repository(
    name = "com_github_boost_spirit",
    build_file = "@//third_party/boost:spirit.BUILD",
    remote = "https://github.com/boostorg/spirit.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-spirit",
    actual = "@com_github_boost_spirit//:spirit",
)

# static_assert

new_git_repository(
    name = "com_github_boost_static_assert",
    build_file = "@//third_party/boost:static_assert.BUILD",
    remote = "https://github.com/boostorg/static_assert.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-static_assert",
    actual = "@com_github_boost_static_assert//:static_assert",
)

# system

new_git_repository(
    name = "com_github_boost_system",
    build_file = "@//third_party/boost:system.BUILD",
    remote = "https://github.com/boostorg/system.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-system",
    actual = "@com_github_boost_system//:system",
)

# test

new_git_repository(
    name = "com_github_boost_test",
    build_file = "@//third_party/boost:test.BUILD",
    remote = "https://github.com/boostorg/test.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-test",
    actual = "@com_github_boost_test//:test",
)

# thread

new_git_repository(
    name = "com_github_boost_thread",
    build_file = "@//third_party/boost:thread.BUILD",
    remote = "https://github.com/boostorg/thread.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-thread",
    actual = "@com_github_boost_thread//:thread",
)

# throw_exception

new_git_repository(
    name = "com_github_boost_throw_exception",
    build_file = "@//third_party/boost:throw_exception.BUILD",
    remote = "https://github.com/boostorg/throw_exception.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-throw_exception",
    actual = "@com_github_boost_throw_exception//:throw_exception",
)

# timer

new_git_repository(
    name = "com_github_boost_timer",
    build_file = "@//third_party/boost:timer.BUILD",
    remote = "https://github.com/boostorg/timer.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-timer",
    actual = "@com_github_boost_timer//:timer",
)

# tokenizer

new_git_repository(
    name = "com_github_boost_tokenizer",
    build_file = "@//third_party/boost:tokenizer.BUILD",
    remote = "https://github.com/boostorg/tokenizer.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-tokenizer",
    actual = "@com_github_boost_tokenizer//:tokenizer",
)

# tuple

new_git_repository(
    name = "com_github_boost_tuple",
    build_file = "@//third_party/boost:tuple.BUILD",
    remote = "https://github.com/boostorg/tuple.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-tuple",
    actual = "@com_github_boost_tuple//:tuple",
)

# type_index

new_git_repository(
    name = "com_github_boost_type_index",
    build_file = "@//third_party/boost:type_index.BUILD",
    remote = "https://github.com/boostorg/type_index.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-type_index",
    actual = "@com_github_boost_type_index//:type_index",
)

# type_traits

new_git_repository(
    name = "com_github_boost_type_traits",
    build_file = "@//third_party/boost:type_traits.BUILD",
    remote = "https://github.com/boostorg/type_traits.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-type_traits",
    actual = "@com_github_boost_type_traits//:type_traits",
)

# typeof

new_git_repository(
    name = "com_github_boost_typeof",
    build_file = "@//third_party/boost:typeof.BUILD",
    remote = "https://github.com/boostorg/typeof.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-typeof",
    actual = "@com_github_boost_typeof//:typeof",
)

# utility

new_git_repository(
    name = "com_github_boost_utility",
    build_file = "@//third_party/boost:utility.BUILD",
    remote = "https://github.com/boostorg/utility.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-utility",
    actual = "@com_github_boost_utility//:utility",
)

# variant

new_git_repository(
    name = "com_github_boost_variant",
    build_file = "@//third_party/boost:variant.BUILD",
    remote = "https://github.com/boostorg/variant.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-variant",
    actual = "@com_github_boost_variant//:variant",
)

# winapi

new_git_repository(
    name = "com_github_boost_winapi",
    build_file = "@//third_party/boost:winapi.BUILD",
    remote = "https://github.com/boostorg/winapi.git",
    tag = BOOST_RELEASE_TAG,
)

bind(
    name = "boost-winapi",
    actual = "@com_github_boost_winapi//:winapi",
)
